export const ErrorCodes = {
  // Auth
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_CREDENTIALS_INVALID: 'AUTH_CREDENTIALS_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',
  AUTH_KEYCLOAK_UNAVAILABLE: 'AUTH_KEYCLOAK_UNAVAILABLE',
  AUTH_REGISTER_FAILED: 'AUTH_REGISTER_FAILED',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  USER_USERNAME_TAKEN: 'USER_USERNAME_TAKEN',
  USER_PHONE_TAKEN: 'USER_PHONE_TAKEN',
  USER_BANNED: 'USER_BANNED',

  // Common
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
